#!/usr/bin/env node
/**
 * THIRD-PARTY-NOTICES.md 생성.
 *
 * MIT·BSD·ISC·Apache 계열은 저작권 고지와 라이선스 전문을 배포물과 함께 제공할 것을
 * 요구한다. Janus는 Vite로 의존성을 번들해 배포하므로 그 의무가 실제로 발생한다.
 *
 * 번들 분석 대신 전체 의존성 집합을 싣는다 — 과다 포함은 안전하고, 과소 포함만
 * 위반이다. 어떤 집합인지는 파일 머리에 밝힌다.
 *
 * 실행: node scripts/generate-notices.mjs [--check]
 *   --check 는 파일을 쓰지 않고 최신인지만 확인한다(CI용).
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const OUTPUT = join(ROOT, 'THIRD-PARTY-NOTICES.md')
const LICENSE_FILES = /^(LICENSE|LICENCE|COPYING|NOTICE)(\.(md|txt))?$/i

/** 직접 의존성 지문 — 플랫폼과 무관하다.
 *
 *  전체 렌더 결과를 비교하면 CI(Linux)와 빌드 머신(macOS)이 영원히 불일치한다.
 *  `pnpm licenses list`가 플랫폼별 바이너리 패키지(@esbuild/*, fsevents 등)를
 *  다르게 내기 때문이다. 잡으려는 실패는 "의존성을 바꾸고 고지를 안 만들었다"이므로
 *  직접 의존성 목록만 비교하면 충분하고, 어디서 돌려도 같은 답이 나온다.
 */
function fingerprint() {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8'))
  const all = { ...manifest.dependencies, ...manifest.devDependencies }
  return Object.keys(all).sort().map((name) => `${name}@${all[name]}`).join('\n')
}

/** 패키지 디렉터리에서 라이선스 전문을 찾는다. 없으면 null — 식별자만 싣는다. */
function licenseText(packageDir) {
  if (!packageDir || !existsSync(packageDir)) return null
  for (const entry of readdirSync(packageDir)) {
    if (!LICENSE_FILES.test(entry)) continue
    const body = readFileSync(join(packageDir, entry), 'utf-8').trim()
    if (body) return body
  }
  return null
}

function collect() {
  const raw = execFileSync('pnpm', ['licenses', 'list', '--json'], {
    cwd: ROOT, encoding: 'utf-8', maxBuffer: 64 * 1024 * 1024
  })
  const grouped = JSON.parse(raw)
  const packages = []
  for (const [license, entries] of Object.entries(grouped)) {
    for (const entry of entries) {
      packages.push({
        name: entry.name,
        versions: (entry.versions ?? []).join(', '),
        license,
        homepage: entry.homepage ?? '',
        text: licenseText((entry.paths ?? [])[0])
      })
    }
  }
  packages.sort((a, b) => a.name.localeCompare(b.name))
  return packages
}

function render(packages) {
  const byLicense = new Map()
  for (const item of packages) {
    byLicense.set(item.license, (byLicense.get(item.license) ?? 0) + 1)
  }
  const summary = [...byLicense.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([license, count]) => `| ${license} | ${count} |`)
    .join('\n')

  const bodies = packages.map((item) => {
    const head = `### ${item.name} ${item.versions}\n\n`
      + `License: ${item.license}${item.homepage ? ` · ${item.homepage}` : ''}\n`
    if (!item.text) return head
    return `${head}\n\`\`\`text\n${item.text}\n\`\`\`\n`
  }).join('\n')

  return `<!-- direct-dependencies:
${fingerprint()}
-->
# Third-party notices

Janus bundles its JavaScript dependencies into the shipped application, so the
notices below travel with the binary. This lists **every package in the
dependency tree**, not only those the bundler retained — over-inclusion is safe,
under-inclusion is not.

Janus itself is Apache-2.0; see [LICENSE](LICENSE).

Generated by \`node scripts/generate-notices.mjs\`. Do not edit by hand.

## Summary

| License | Packages |
|---|---|
${summary}

Total: ${packages.length} packages.

## Packages

${bodies}`
}

const packages = collect()
const rendered = render(packages)

function recordedFingerprint(text) {
  const match = text.match(/<!-- direct-dependencies:\n([\s\S]*?)\n-->/)
  return match ? match[1] : null
}

if (process.argv.includes('--check')) {
  if (!existsSync(OUTPUT)) {
    console.error('THIRD-PARTY-NOTICES.md is missing. Run: pnpm notices')
    process.exit(1)
  }
  const current = readFileSync(OUTPUT, 'utf-8')
  if (recordedFingerprint(current) !== fingerprint()) {
    console.error(
      'THIRD-PARTY-NOTICES.md does not match package.json. Run: pnpm notices'
    )
    process.exit(1)
  }
  console.log('third-party notices match the declared dependencies')
} else {
  writeFileSync(OUTPUT, rendered)
  console.log(`wrote ${OUTPUT} (${packages.length} packages)`)
}
